# Generated by Django 5.2.8 on 2025-11-12 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id_livro', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('isbn', models.CharField(max_length=100)),
                ('disponivel', models.CharField(choices=[('Disponível', 'Disponivel'), ('Empretado', 'Emprestado')], default='Disponível', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=4)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id_emprestimo', models.IntegerField(primary_key=True, serialize=False)),
                ('data_emp', models.DateField()),
                ('dev_prev', models.DateField()),
                ('data_dev', models.DateField()),
                ('status', models.CharField(choices=[('Finalizado', 'Finalizado'), ('Em andamento', 'Andamento'), ('Atrasado', 'Atrasado')], default='Em andamento', max_length=12)),
                ('id_livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.livro')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.usuario')),
            ],
        ),
    ]
